### ISSUE TITLE
Is Exclusive Lock really needed? Do you use it?

### ISSUE THREAD

**Issue by etamponi** [porcupie/rbd-docker-plugin#10]
To be able to mount rbd volumes, I needed to set `rbd default features = 3`, that is, I had to disable  exclusive locking. This makes the plugin work, but when I check in the logs I see that it complains about not being able of taking the lock on the volume:

```
2016/09/05 20:10:49 driver.go:360: INFO: API Mount({welcome 8e79f14fca1ae71f2f84e707a15a173d9f5b77afa64a3824d31dc55ec061a327})
2016/09/05 20:10:49 driver.go:384: ERROR: locking RBD Image(welcome): exit status 16
2016/09/05 20:10:49 driver.go:568: INFO: API Unmount({welcome })
2016/09/05 20:10:49 driver.go:612: ERROR: unmounting device(/dev/rbd0): exit status 32
```

So my question is: I didn't see any reference to disabling the exclusive lock in the README, so I assume that your kernel works fine!

Which version of Ceph do you use? And which kernel?

```
# ceph --version
ceph version 10.2.2 (45107e21c568dd033c2f0a3107dec8f0b0e58374)
```

```
# uname -a
Linux ubuntu 4.4.8 #2 SMP Tue Jun 7 12:10:44 AEST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by porcupie** [comment]
Yes we do use exclusive Ceph RBD locks.  We tend not to rely on latest of anything, or we're slow on uptake anyway: CentOS 7.x, kernel 3.10.x, Docker 1.9, Ceph 0.94.8

**Comment by etamponi** [comment]
As I expected! Thanks! Too bad, `ceph-deploy` does not work anymore to
install Ceph Hammer on Ubuntu because of a packaging issue. I will try to
install Ceph manually.

Il 06 set 2016 1:23 AM, "Damian Martinez" notifications@github.com ha
scritto:

**Comment by etamponi** [comment]
Ok, it was an issue with my code, and the errors were actually lecit. I am gonna close this.
