### ISSUE TITLE
/VolumeDriver.List should also show unmounted volumes

### ISSUE THREAD

**Issue by etamponi** [porcupie/rbd-docker-plugin#11]
Right now, `/VolumeDriver.List` shows only volumes that are currently mounted on a running container. This is clearly different from what I'd expect from `docker volume ls`, because for the `local` driver, it shows all the volumes, even if unmounted.

Moreover, the documentation about `/VolumeDriver.List` clearly states that, in the response, _Mountpoint is optional_ [[link](https://docs.docker.com/engine/extend/plugins_volume/#/volumedriver-list)].

What do you think? I'd like to contribute a patch if I am able to, but I'd first like to hear from you if you think this is the correct interpretation.

**Comment by porcupie** [comment]
Thanks - Fixed in v2.0.
