### ISSUE TITLE
Ignore temporary / unnamed volumes from the Dockerfile VOLUME directive

### ISSUE THREAD

**Issue by timcharper** [porcupie/rbd-docker-plugin#12]
If I launch a docker container that has a line such as the following in the Dockerfile (and have create enabled in the plugin):

```
VOLUME ["/var/lib/grafana", "/var/lib/grafana/plugins", "/var/log/grafana", "/etc/grafana"]
```

... and I don't specify these volumes at launch, then I get 4 auto-created, randomly named volumes.

I ran this:

```
 docker run --rm -it -v grafana-sw:/data --volume-driver=rbd grafana/grafana:2.6.0 bash
```

And I got these.

```
# rbd list
24f25deb3960903b45b3b39da53bce0a748013b05336173a08cb044494b30465
4e98144957643202906b70b55d98586fde2f913deacd270f92e0462078e73576
882da98969f11e7eff599fa9f6c4562224045813f2bba523d00691e903ecda26
a0551cbaa1c768483762c804c645462d5bb2023b05d05e2c14dc0c9a513a6549
grafana-sw
```

After I quit the docker container and run it again, more images are created:

```
# rbd ls
18a11aa4c6a9805b0751515696ef5c2f7bea7a9f5fa40517b80f42532b9c4c49
24f25deb3960903b45b3b39da53bce0a748013b05336173a08cb044494b30465
3216c856bc5e28519493efa8523aee0ed866036dc94c395aa39ec79abec0912c
4e98144957643202906b70b55d98586fde2f913deacd270f92e0462078e73576
69db8e3abd9c884ca5a2c60436645e17f8dd1577bc4b2f28201ed7e10962dc14
703ad6adb106670208f419a8567ad10ecf4ea669da683154364a586e71178b02
882da98969f11e7eff599fa9f6c4562224045813f2bba523d00691e903ecda26
a0551cbaa1c768483762c804c645462d5bb2023b05d05e2c14dc0c9a513a6549
grafana-sw
```

Ideally, the rbd plugin would detect these anonymous volumes and just let them be written on the filesystem, and cleaned up when the container quits.

**Comment by timcharper** [comment]
A workaround was brought to my attention; looks like this might not be needed after all. https://mesosphere.github.io/marathon/docs/external-volumes.html

Might be nice if rbd-docker-plugin cowardly refuses to create these anonymous volumes. Could be as simple as matching a regex

**Comment by porcupie** [comment]
This seems to be an issue with Docker and not the plugin.  IOW docker API has requested the volume named "18a11aa4c6a9805b0751515696ef5c2f7bea7a9f5fa40517b80f42532b9c4c49" to be created - the plugin and RBD does not have this capability itself.  Docker is assigning a UUID to an "anon" volume and requesting it to be created by the plugin.

Some more info on #3

Seems outside the scope of this plugin?

**Comment by porcupie** [comment]
Seems Related to #3

**Comment by timcharper** [comment]
Thanks, @porcupie !
