### ISSUE TITLE
Mount image read only

### ISSUE THREAD

**Issue by tsaridas** [porcupie/rbd-docker-plugin#2]
Docker support read only image mounts so does ceph. It would be useful to have images being mounted as read only with the plugin too.

Tried to see if we can get the variable RO from docker but I couldn't.

**Comment by porcupie** [comment]
Interesting, will have to look into this and figure out where the :ro will get sent or if we have to again overload the volume name with another decorator for read-only.  

If we had this feature, it could also allow an RBD volume to be used by multiple consumers (if they were all read-only or at most 1 writer), but that would also require changes to how RBD exclusive locks are managed.

**Comment by tsaridas** [comment]
my research shows that docker needs to pass this variable to the plugin which currently it doesn't.

I created : https://github.com/docker/docker/issues/23051

**Comment by porcupie** [comment]
Seems like either they do not understand the use-case or are unwilling to support it. Closing ticket for now
