### ISSUE TITLE
Unable to mount device

### ISSUE THREAD

**Issue by CBR09** [porcupie/rbd-docker-plugin#4]
Hi everyone and @porcupie 
I've test rbd-docker-plugin on my environment and got issue: Uname to mount device
OS: ubuntu 14.04
Run rbd-docker-plugin:

>  RBD_DOCKER_PLUGIN_DEBUG=1 rbd-docker-plugin --create --size=10

Create docker container with rbd hello image and got error

> docker run --volume-driver=rbd --volume hello:/mnt/foo -it ubuntu /bin/bash
> docker: Error response from daemon: VolumeDriver.Mount: Unable to mount device.

rbd-docker-plugin logs:

> rbd-volume-plugin: 2016/06/02 09:43:15 main.go:92: INFO: starting rbd-docker-plugin version 1.1.1
> rbd-volume-plugin: 2016/06/02 09:43:15 main.go:93: INFO: canCreateVolumes=%!q(bool=true), removeAction="ignore"
> rbd-volume-plugin: 2016/06/02 09:43:15 main.go:103: INFO: Setting up Ceph Driver for PluginID=rbd, cluster=, user=admin, pool=rbd, mount=/var/lib/docker-volumes, config=/etc/ceph/ceph.conf, go-ceph=%!s(bool=false)
> rbd-volume-plugin: 2016/06/02 09:43:15 driver.go:115: INFO: newCephRBDVolumeDriver: setting base mount dir=/var/lib/docker-volumes/rbd
> rbd-volume-plugin: 2016/06/02 09:43:15 main.go:127: INFO: Creating Docker VolumeDriver Handler
> rbd-volume-plugin: 2016/06/02 09:43:15 main.go:131: INFO: Opening Socket for Docker to connect: /run/docker/plugins/rbd.sock
> 
> rbd-volume-plugin: 2016/06/02 09:44:42 driver.go:695: DEBUG: parseImagePoolNameSize: "hello": ["hello" "" "" "hello" "" ""]
> rbd-volume-plugin: 2016/06/02 09:44:42 driver.go:503: INFO: API Path request(hello) => /var/lib/docker-volumes/rbd/rbd/hello
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:321: INFO: API Mount(hello)
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:695: DEBUG: parseImagePoolNameSize: "hello": ["hello" "" "" "hello" "" ""]
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--pool" "rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "info" "hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--pool" "rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "lock" "add" "hello" "ceph"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--pool" "rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "map" "hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/sbin/blkid" ["blkid" "-o" "value" "-s" "TYPE" ""] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:384: WARN: unable to detect RBD Image(hello) fstype: exit status 2
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/bin/mount" ["mount" "-t" "xfs" "" "/var/lib/docker-volumes/rbd/rbd/hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:402: ERROR: mounting device() to directory(/var/lib/docker-volumes/rbd/rbd/hello): exit status 32
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:946: INFO: unlockImage(rbd/hello, ceph)
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--pool" "rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "lock" "list" "hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:967: DEBUG: found lines matching ceph:
> [client.4177 ceph 10.76.0.79:0/1624486433]
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--pool" "rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "lock" "rm" "hello" "ceph" "client.4177"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:43 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "unmap" ""] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:522: INFO: API Unmount(hello)
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:695: DEBUG: parseImagePoolNameSize: "hello": ["hello" "" "" "hello" "" ""]
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:550: WARN: Volume is not in known mounts: will attempt limited Unmount: rbd/hello
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:1125: DEBUG: sh CMD: &{"/bin/umount" ["umount" "/dev/rbd/rbd/hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:565: ERROR: unmounting device(/dev/rbd/rbd/hello): exit status 1
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "unmap" "/dev/rbd/rbd/hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:946: INFO: unlockImage(rbd/hello, ceph)
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:1125: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "--pool" "rbd" "--conf" "/etc/ceph/ceph.conf" "--id" "admin" "lock" "list" "hello"] [] "" <nil> <nil> <nil> [] %!q(_syscall.SysProcAttr=<nil>) %!q(_os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
> rbd-volume-plugin: 2016/06/02 09:44:44 driver.go:959: ERROR: image not locked or ceph rbd error: %!s(<nil>)

Thanks

**Comment by vincepii** [comment]
If the hello rbd image already exists and there is no filesystem on it, then the plugin won't create it (the fs), at least this is what I have observed.

In this case, map the image and make a filesystem on it, something like:

```
rbd map hello
mkfs.ext4 /dev/rbd/rbd/hello
rbd unmap hello
```

**Comment by CBR09** [comment]
Thanks @vincepii, I've tried make a filesystem on hello image, but same issue.

**Comment by porcupie** [comment]
Looks like maybe rbd is not returning the mapped device?  For example, it's not detecting your Filesystem type because the device is blank:

```
blkid -o value -s TYPE ""
```

@CBR09  Can you rbd map your image and see what it outputs - it should be something like `/dev/rbd0`:

```
rbd map hello
```

We might be able to use the "named" device path as a default if `rbd` binary doesn't return text string.  (e.g. the `/dev/rbd/pool/image` format, assuming no naming conflicts).

**Comment by CBR09** [comment]
Hi @porcupie,
Yes, I've map hello image and rbd map return nothing.

> root@ceph:~# rbd ls
> hello
> root@ceph:~# rbd map hello
> root@ceph:~# rbd showmapped
> id pool image snap device  
> 1  rbd  hello -    /dev/rbd1 

So, How can I make rbd-docker-plugin work?
Thanks

**Comment by porcupie** [comment]
@CBR09 I made a workaround in the code - could you try v1.2.1 and see if it solved the issue?

**Comment by CBR09** [comment]
Hi @porcupie ,
I've test with v1.2.1, it solved my issue.
Thanks
